### ISSUE TITLE
question about demo

### ISSUE THREAD

**Issue by johnfelipe** [MicroHealthLLC/mCMS#1]
Do u have a demo live url or may be screenshots?

**Comment by bluenevus** [comment]
Working on the user manual, that should have a bunch of screenshots and we will post here.  We are also working the install guide to make it much easier to install. Its under heavy heavy development so its probably not best to put this out now until the features have been stabilized.  We are probably a few months away from it fully stabilizing.

**Comment by bluenevus** [comment]
will get demo up once its pretty stable
