### ISSUE TITLE
on new data entry default all start dates and date identified dates to today

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#104]
![image](https://cloud.githubusercontent.com/assets/3675043/26728429/32ebfaca-4778-11e7-96f6-12d376899dbb.png)

**Comment by bluenevus** [comment]
There are still start dates that don’t default entry to today like action, documents, appointment

 

 

-- 

Vr, Frank

 

If you get an email that looks like its coming from me such as “Secure message from Frank Tucker” or some dropbox message…its Phishing, don’t click the link.  If you did click the link run antivirus and completely clean your outlook rules!!!! Like outlook.exe /cleanrules.  Notice, my emails are digitally signed.

**Comment by b-solution** [comment]
i think that's all.
