### ISSUE TITLE
RSS is not saving and NOT displaying

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#127]
![image](https://user-images.githubusercontent.com/3675043/29129500-9e069604-7cec-11e7-8eb9-a1e3ca2d6606.png)

**Comment by b-solution** [comment]
try to "rake assets:precompile RAILS_ENV=production "
and restart the server
It's working on my side. If it still not saving let me know.

**Comment by bluenevus** [comment]
can we push the https changes in the code so that when someone pulls it, there is no text file config they will have to do?
