### ISSUE TITLE
remove submenus

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#138]
Now that we have a tab menu, can we remove the submenus to simplify the menu so that clickign occupational history goes straight to this page?

![image](https://user-images.githubusercontent.com/3675043/29416274-8bc9be88-8333-11e7-8b03-8a588b077853.png)

the same for profile, medical and social for consistency.

**Comment by b-solution** [comment]
should i import print button to tabs?

**Comment by bluenevus** [comment]
I think so so they know what it will print
