### ISSUE TITLE
can we make the intranet right menu a different color from the client right menu?

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#148]
This way they know they are on the client menu vs on the intranet menu
![image](https://user-images.githubusercontent.com/3675043/29461339-618d87d2-83f9-11e7-9796-cbb7272d0dec.png)

![image](https://user-images.githubusercontent.com/3675043/29461359-6ac04ce0-83f9-11e7-9934-e7b3457af462.png)

**Comment by b-solution** [comment]
Now, when you go to setting page => theme, you will find 2 section (admin/client) you can define the theme of each section. this solution is better i think.

**Comment by bluenevus** [comment]
even though there are two sections and both have different colors, the intranet menu and the client menu is still the same color.  Now, I did click text editor and that specifically changed the color but only there

**Comment by b-solution** [comment]
my bad. fixed again
