### ISSUE TITLE
rather than go to this page to view the information, can we go to the edit screen for all pages?

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#155]
![image](https://user-images.githubusercontent.com/3675043/29465797-83fe9bc6-8408-11e7-9def-66c7d7769e8b.png)

please put the menu functions on the edit screen here 
![image](https://user-images.githubusercontent.com/3675043/29465831-9aa74f12-8408-11e7-8aba-52b5f5ebdd27.png)

This will save users a click and paging

**Comment by b-solution** [comment]
Some user does not have the edit permission, only view permission. So how can fix that.?

**Comment by bluenevus** [comment]
oooh, I forgot about that.  can the edit screen be greyed out on load then when they click edit given they have the permissions, it unlocks the fields to white so they can edit it?  Just trying to reduce the number of screens
