### ISSUE TITLE
when creating or editing note templates allow them to be limited to organizations

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#162]
![image](https://user-images.githubusercontent.com/3675043/29619352-e32af75a-87e8-11e7-9fac-999aa3dd5924.png)

currently, its viewable by all.  I would like note templates to be organization specific.  Therefore, only admins can create templates viewable by everyone.  If they are not an admin and can create a template, the template can only be created for the organization they are assigned.  They can also share the template with other organizations so they can use it but not change the template.

**Comment by b-solution** [comment]
@bluenevus Did add organization on note template but only admin can create it and select what organization to display
