### ISSUE TITLE
sometimes the attachment shows, sometimes it doesn't but what is supposed to show is My Documents

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#165]
sometimes the attachment shows, sometimes it doesn't.  Attachments should be removed

![image](https://user-images.githubusercontent.com/3675043/29717901-eef7783c-897e-11e7-8faf-5b291dd92389.png)

**Comment by b-solution** [comment]
the attachment section is on /users/ID. this is the only link that you can see it

**Comment by bluenevus** [comment]
I think we just want to show the tabs for every area including the attachment so it shows like the picture all the time
