### ISSUE TITLE
SMS notification

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#19]
In the profile, allow the case manager to select contact preferences for the user
If the user has no contact preferences, they will NOT get any email or sms
They can check email and which email addresses it will notify
They can check which telephone number and it will notify by sms
SMS will be through Twilio for which the api key is configured in the user interface

**Comment by b-solution** [comment]
add this in application.yml

TWILIO_ACCOUNT_SID: "AC33d5c4d82dd53e3cb4c280f778306fa3"
TWILIO_AUTH_TOKEN: "bdbec2b99c3ddb9e4fd36cd0751d060c"
TWILIO_PHONE_NUMBER_full: "+18329003291"
