### ISSUE TITLE
Timeline right menu slider request

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#195]
![image](https://user-images.githubusercontent.com/3675043/30601987-4be85942-9d31-11e7-930d-5fc78a800634.png)

Can we make the timeline a right sided menu like the left side menu that slides out when click and the main container contents resize?  When clicked it slides out and in.

**Comment by b-solution** [comment]
Click to Timeline button :)

**Comment by bluenevus** [comment]
Thanks.  It goes to a page vs a slider on the right
