### ISSUE TITLE
SVG Edit doesn't work outside the container and should be in the container

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#200]
![image](https://user-images.githubusercontent.com/3675043/30613679-ffb18474-9d56-11e7-8e72-109d9265ab97.png)

**Comment by b-solution** [comment]
![svg umed](https://user-images.githubusercontent.com/5988861/31122021-a234dbc2-a83a-11e7-9fec-bb932865abb5.png)

It is working for me here

**Comment by bluenevus** [comment]
started working
