### ISSUE TITLE
Serial Number issues

### ISSUE THREAD

**Issue by drupretys** [MicroHealthLLC/mCMS#227]
Admin>User
Serial Number missing

![image](https://user-images.githubusercontent.com/33326155/32899494-23ae7136-cab9-11e7-9b35-5487eb7b8554.png)

**Comment by bluenevus** [comment]
The issue is that because the numbers are serial in nature, its confusing people in thinking that it shows 35 entries however, when you actually look at the last number which is the ID it says 45.  Probably best to create 11 digit identifier thats always unique
