### ISSUE TITLE
I get logged off from MCMS

### ISSUE THREAD

**Issue by drupretys** [MicroHealthLLC/mCMS#229]
Everytime I try  to go from Home page to other places  such  as Client  search etc  I get  logged off from the mCMS. Please check the screen shot . On the left upper side of  the screen  you can  view  that.
Removal may  be  the  best  choice.
![image](https://user-images.githubusercontent.com/33326155/32905728-d3e7ede8-cac8-11e7-948a-5a928b00bec3.png)
.

**Comment by bluenevus** [comment]
This looks like the message above when you are leaving the client screen is causing confusion so we just need to remove that
