### ISSUE TITLE
Drop down and  Units

### ISSUE THREAD

**Issue by drupretys** [MicroHealthLLC/mCMS#230]
Search Client>John>Core Demographics
Title :  No drop dropdown with Mr, Mrs,  Ms, Dr.
Height/  Weight : can't write Unitx  such  as inches or  feet or pounds (lb)
![image](https://user-images.githubusercontent.com/33326155/32910568-954bd838-cad7-11e7-94e1-fd28453ec86a.png)

**Comment by b-solution** [comment]
should i replace Title with dropdown or make a dropdown next to title ??

**Comment by bluenevus** [comment]
Drop-down next to title

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
