### ISSUE TITLE
CSV does  nothing , it is almost  at top upper right corner

### ISSUE THREAD

**Issue by drupretys** [MicroHealthLLC/mCMS#236]
![image](https://user-images.githubusercontent.com/33326155/32966615-597b1612-cba8-11e7-8f7c-98e1707ca0b9.png)

**Comment by b-solution** [comment]
60% done care record 0%, occupation record(50%), Socioeco record(100%) and medical record(100%) and profile_record 70%

**Comment by b-solution** [comment]
updates:
case record 0%, occupation record(100%), Socioeco record(100%) and medical record(100%) and profile_record 90%

**Comment by b-solution** [comment]
updates: case record 40%

**Comment by b-solution** [comment]
updates:
case record 100%, occupation record(100%), Socioeco record(100%) and medical record(100%) and profile_record 100%
