### ISSUE TITLE
Cant add more contacts (max 2?), Once contact tab is used it takes back  to Johns  profile.

### ISSUE THREAD

**Issue by drupretys** [MicroHealthLLC/mCMS#237]
![image](https://user-images.githubusercontent.com/33326155/32967979-9460a2f6-cbad-11e7-917a-88620e4c36c7.png)
![image](https://user-images.githubusercontent.com/33326155/32968005-a7e476a4-cbad-11e7-93ae-36d9512b5f2e.png)

**Comment by LAlexMHllc** [comment]
Was able to add more than 2 contacts to John. I stopped at 4 contacts.
