### ISSUE TITLE
( Dropdown Menu) Not functioning fully on User Insurance on mCMS

### ISSUE THREAD

**Issue by drupretys** [MicroHealthLLC/mCMS#240]
**Environment** : Microhealth device, os and  a chrome browser

**Steps to reproduce**:
 search client>John>User Insurance>Health>Click ( Insurance , relationship, Insured name, Insurance type drop down one  at a  time)

 **Expected  result:**
User should  be  able to search other  insurance  company through the  eye glass from  a drop down at Insurance.
Use should  be able to type others when  they  are in a Relationship drop down.
User should be the able to see John Patient only on Insured name.
User should be able to select more than one insurance type if  they have dental, health, and  vision.

**Actual Result:**

User is  not able to search other insurance companies through eye glass.
User is not  able to specify who other is in the  Relationship drop down.
User is able to see other patients name in Insured name.
User is not able to select  more than one insurance if they have   more than one.

**Screen Shot**:
![image](https://user-images.githubusercontent.com/33326155/33040190-50904448-ce08-11e7-892d-b868ee878a90.png)

**Comment by bluenevus** [comment]
clicking actions does nothing

![image](https://user-images.githubusercontent.com/3675043/34494948-dba84682-efc0-11e7-878d-41adb6b949ff.png)
