### ISSUE TITLE
(Color ) of tabs are  dull

### ISSUE THREAD

**Issue by drupretys** [MicroHealthLLC/mCMS#241]
Environment : Microhealth device, os and a chrome browser

Steps to reproduce:
search client>John>Look buttons/tabs  which starts at left upper side  of  the  screen  :  core demographics--- ends at  Organization

Expected result:
User should be able to see nice colored tab like  that  of Twitter,  sky bluish with white alphabets

Actual Result:
User is not able to see nice color like  that  of  twitter logo, it is dull grayish and  grayishblack  alphabets

 Screen Shot ( Actual  color)

![image](https://user-images.githubusercontent.com/33326155/33281859-acbcd36e-d374-11e7-96d8-09984916f1a9.png)
 
Screen Shot (Color Required) :  Example of  Twitter color
![image](https://user-images.githubusercontent.com/33326155/33281914-e06fec50-d374-11e7-8e2e-cac3f8c2197d.png)

Link of Research for  the  color:

https://optinmonster.com/which-color-button-converts-best/

**Comment by bluenevus** [comment]
maybe more like the middle twitter color.  the color we have right now is not quite twitter

**Comment by bluenevus** [comment]
maybe even like salesforce 
![image](https://user-images.githubusercontent.com/3675043/33722282-8e6ba41a-db37-11e7-8519-cc3bf73e3831.png)

**Comment by drupretys** [comment]
agree

**Comment by bluenevus** [comment]
Lisa Alexander can we change the color of the grids header to #B2C8D6
and the tabs to  9BACBC.  Tabs that are moused over should be #
DBC2A4 and when they are selected and now in focus 
F59B69.  This is the palate here http://www.colourlovers.com/palette/3283740/Grapefruit  This way we can stick to a scheme.
