### ISSUE TITLE
add action menu and move new documents there for consistency

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#243]
![image](https://user-images.githubusercontent.com/3675043/33720363-b721e5fa-db31-11e7-961a-ee1c0a0fd50e.png)

move show/hide next to right drop down list

**Comment by LAlexMHllc** [comment]
Add "Action" drop-down menu select with "New Documents" option; then remove "New Documents" button.
![document_manager_main_screen_action](https://user-images.githubusercontent.com/11938477/33895589-d55c845c-df2e-11e7-82fb-5757a6ec58c9.jpg)
