### ISSUE TITLE
( Dropdown)Nonfunctional eyeglass, Title, Citizen

### ISSUE THREAD

**Issue by drupretys** [MicroHealthLLC/mCMS#244]
Environment : Microhealth device, os and a chrome browser

Steps to reproduce:
search client>John>Look Profile>Title and Citizen drop down eyeglasses functionless

Expected result:
User should be able to search Title such  as Dr., Ms., etc through  eyeglass search dropdown
User should  be  able to search Citizen  such as French,  German Italian etc also through eyeglass drop down.

Actual Result:
User is not able to use the eyeglasses on the drop down Title and  Citizen . Nothing happens when user tries to use eyeglass search at  dropdown.

Screen Shot 

[image](https://user-images.githubusercontent.com/33326155/33729105-9d841668-db4a-11e7-9d0c-90270320b13a.png)

**Comment by bluenevus** [comment]
enumeration not setup
