### ISSUE TITLE
(SKILL TYPE DROPDOWN) non functional

### ISSUE THREAD

**Issue by drupretys** [MicroHealthLLC/mCMS#245]
Environment : Microhealth device, os and a chrome browser

Steps to reproduce:
search client>John>Occupational history>skill>new awesome skill>skill type space  with  drop down arrow  and eyeglass nonfunctional

Expected result:
User should be able to search or type SKILL TYPE at the space or search through eyeglass

Actual Result:
User is not able to use the  eyeglasses/type  on the drop down SKILL TYPE space, it is  non functional.

Screen Shot
![image](https://user-images.githubusercontent.com/33326155/33732370-4c6bc370-db54-11e7-9379-5ca197dce647.png)

**Comment by bluenevus** [comment]
enumeration not setup
