### ISSUE TITLE
Can we have the other theme options from smartadmin

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#247]
![image](https://user-images.githubusercontent.com/3675043/33735334-0577783e-db5d-11e7-8440-b768c48cb5f3.png)

**Comment by b-solution** [comment]
@bluenevus do you have the new smart admin ?

**Comment by bluenevus** [comment]
Yes.  I'll attach it on teams

On Mar 9, 2018 2:29 PM, bilel-kedidi <notifications@github.com> wrote:

@bluenevus<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbluenevus&data=01%7C01%7Cfrank.tucker%40microhealthllc.com%7Cd160aedd2eae46dd5ad508d585f417c2%7C487ea2d67ea04a4b87736f4833ed2108%7C0&sdata=JvhrcnfP5SVagmWK5Y8teRrAwq3MH8WZyOvsdI5d1%2Bs%3D&reserved=0> do you have the new smart admin ?
