### ISSUE TITLE
filter button on search screen is the wrong color

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#248]
the filter should be colored like the 2nd image consistent with the rest of the app

![image](https://user-images.githubusercontent.com/3675043/33779808-65b9f428-dc1c-11e7-887c-287d919e2601.png)

![image](https://user-images.githubusercontent.com/3675043/33779798-5abfe78a-dc1c-11e7-85cc-6a624388bed6.png)

**Comment by b-solution** [comment]
@LAlexMHllc Did you this error, i already have a different color in search client page

**Comment by LAlexMHllc** [comment]
Yes, was adjusting colors in the middle of a pull. Some CSS to be updated later.
