### ISSUE TITLE
can we make all save buttons the same size, the same location on the page and big and green?

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#249]
can we make all save buttons the same size, the same location on the page and big and green?  Also for consistency can we have a cancel button that is grey to the left of every save button.  Like the 2nd image

![image](https://user-images.githubusercontent.com/3675043/33779959-f8ccce70-dc1c-11e7-9cec-81d3f25100b1.png)

like this
https://support.pipedrive.com/hc/en-us/article_attachments/204110109/add_activity.gif

**Comment by b-solution** [comment]
and now?
