### ISSUE TITLE
clicking the link to the all files should take you to the respective edit screen for consistency

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#261]
![image](https://user-images.githubusercontent.com/3675043/33907034-ca7f857a-df51-11e7-9936-cb65cc2141bb.png)

**Comment by LAlexMHllc** [comment]
Example:
After clicking "Amvets" from the All Files table, the html address should be https://cms.microhealthllc.com/affiliations/2/edit so a user can edit the item.
