### ISSUE TITLE
when on a client screen, clicking home should take you back to the client's demographics

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#265]
![image](https://user-images.githubusercontent.com/3675043/33948517-0b7e41a8-dff5-11e7-80f4-1a55ff75b619.png)

right now, if you click home on the breadcrumb, it takes you to here https://cms.microhealthllc.com/
however, when you are on a client, home on the breadcrumb means here.  back to the client demographics where you started https://cms.microhealthllc.com/persons/2 for the client's record you are looking.  Therefore RENAME THE HOME in the breadcrumb to Client and take them to the client profile in the breadcrumb

**Comment by b-solution** [comment]
this is solved in #278
