### ISSUE TITLE
breadcrumbs should be navigational elements based on the menu on the left

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#266]
for example, if I'm on a case, then its Home -- case record -- case name

navigating case record simply takes me to the case record menu and navigating home takes me to the client's demographics.  Can we do this for all the breadcrumbs so they align with the menuing on the left of the image below?

![image](https://user-images.githubusercontent.com/3675043/33948663-6d98dfec-dff5-11e7-831e-988c38e4d687.png)

**Comment by bluenevus** [comment]
If you see here, it says home but it doesn't have Socioeconomic history
![image](https://user-images.githubusercontent.com/3675043/33953840-78a0cfc6-e004-11e7-8ca9-2e2b4a04b1ef.png)

**Comment by bluenevus** [comment]
If you see here it says home but not Health History in the breadcrumb
![image](https://user-images.githubusercontent.com/3675043/33953858-885e8b42-e004-11e7-979e-21165d1acc03.png)

**Comment by bluenevus** [comment]
If you see here it says home but not occupational history in the bread crumb
![image](https://user-images.githubusercontent.com/3675043/33953877-9655ff14-e004-11e7-86fe-0e9ce35350bd.png)

**Comment by bluenevus** [comment]
If you see here it says home but not Demographics in the breadcrumb
![image](https://user-images.githubusercontent.com/3675043/33953897-a5d0a886-e004-11e7-89fd-b52adf291b82.png)

**Comment by bluenevus** [comment]
and here its completely missing the breadcrumb when you search a client and select when it should just go to the client profile screen rather than have 2 different screens

![image](https://user-images.githubusercontent.com/3675043/33953923-bfb68504-e004-11e7-98e2-9a2d0f4a4a3a.png)

**Comment by b-solution** [comment]
linked to all breadcrumbs issues

**Comment by LAlexMHllc** [comment]
After selecting a person from the Clients table on the "Search Client" screen, the user should see:
1. https://cms.microhealthllc.com/profile_record as the html address, NOT https://cms.microhealthllc.com/persons/2
2. "Client Profile" menu nav active, NOT "Search Client" menu nav active
3. "Client Profile" breadcrumb above tabs

![search_client__client_profile](https://user-images.githubusercontent.com/11938477/34303537-d761b1be-e703-11e7-892d-a3ac3b44d49b.jpg)
