### ISSUE TITLE
Fix the html address, active menu nav, and breadcrumb for INITIAL Client Profile screen display after Search Client selection

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#269]
![image](https://user-images.githubusercontent.com/3675043/34015257-e68068b6-e0eb-11e7-9380-71240e4e065d.png)

**Comment by LAlexMHllc** [comment]
The requirement is the screen that would display if "Client Profile" menu nav was clicked from 
https://cms.microhealthllc.com/persons/2

EXAMPLE of requirement

![admin_clients_screen__profile_record](https://user-images.githubusercontent.com/11938477/34414489-9dd3d748-ebb7-11e7-8791-98e397748385.jpg)
