### ISSUE TITLE
Can we add a menu on the left next to home called timeline and suface the timeline of all cases in the main container?

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#276]
![image](https://user-images.githubusercontent.com/3675043/34055466-3f5a79d4-e19d-11e7-8704-847f4a01572a.png)

upon select of a client, make that the first screen they see as opposed to the demographics

Remove the timeline slider function

Increase the size of the fonts for better visibility of the contents of the slider that is moved to the main container

**Comment by b-solution** [comment]
now we have link ( in action dop down ) to redirect to timeline page

**Comment by bluenevus** [comment]
Thanks but can we have the link in the left hand side tree under Case Records that says Case Timeline

--- Vr Frank

**Comment by bluenevus** [comment]
Thanks but can we have the link in the left hand side tree under Case Records that says Case Timeline
