### ISSUE TITLE
Restore Recaptcha

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#28]

**Comment by b-solution** [comment]
try to check the application.yml, the token and the domain

**Comment by bluenevus** [comment]
token is there, domain is there

**Comment by bluenevus** [comment]
I also thought maybe the gem is missing so I did a gem install recaptcha and restarted
still nothing

**Comment by b-solution** [comment]
use RECAPTCHA_PUBLIC_KEY not RECAPTCHA_PUBLIC_KEY_BIS
