### ISSUE TITLE
IMPORTANT ISSUE THROUGHOUT APP: Link to Edit screen instead of Show screen when user has permissions

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#319]
**NOTE: HOLD ON THIS FOR NOW**

Throughout the app, when a user has permission to edit info, the screen that should display is the Edit screen, NOT the Show screen. This way users can edit a record without having to select Edit from the drop-down select and going to another screen. Be sure to update all Edit screens that only have the main content to edit, to include all of the sub-tables shown on the Show screen as well.

**Comment by b-solution** [comment]
Untill now, i have make almost the models to point to edit page when they have permission.
If you found a model that does not have this logic, please let me know.
