### ISSUE TITLE
add percent done for needs, goals and plans

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#32]
![slide18](https://cloud.githubusercontent.com/assets/3675043/24623226/ba0a6e7e-1875-11e7-904a-687614ae0b56.PNG)

**Comment by b-solution** [comment]
done

**Comment by bluenevus** [comment]
pure awesomeness

**Comment by bluenevus** [comment]
the roll up of the percentage doesn't add up.  You can see 40% and 30% of the plans doesn't equal 30% of goal.  so it its the average of the two.  40+30 /2  40% for task 1 and 30% for task 2 and because there are only 2 plans, you divide it by two is it 35% complete as 70/2 is 35%.  The same would go for goals to roll up to needs
