### ISSUE TITLE
Tried to edit Client Contact Info for FAX and several issues occurred

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#321]
Tried to edit a CLIENT profile_record screen, Extended Demographics tab, Fax tab entry.
Result:
A unedited entry was deleted, the entry that was supposed to be edited was duplicated without including the edits, and the error message occurred:
"2 errors prohibited this extend_demography from being saved:
Faxes fax number has already been taken
Faxes fax type has already been taken"

Screenshot after error showing removal of an unedited FAX with duplicate entries (not even one with edits)

![failed_attempt_edit_fax__fax_removal__duplicate_faxes](https://user-images.githubusercontent.com/11938477/34386326-1fc969f6-eaf6-11e7-89ad-0305fed767fe.jpg)

**Comment by b-solution** [comment]
please retry to recreate this issue
