### ISSUE TITLE
Remove "New Attempt" from ADMIN Surveys table

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#327]
Example

![surveys_screen_new_attempt_column](https://user-images.githubusercontent.com/11938477/34392393-df12339c-eb19-11e7-9ce0-82fad1cb9567.jpg)

**Comment by b-solution** [comment]
i think you are not admin in this page !!!!

**Comment by b-solution** [comment]
![screenshot from 2017-12-29 19-32-59](https://user-images.githubusercontent.com/5988861/34444576-5e868266-eccf-11e7-873d-dc93b8b84b33.png)

**Comment by LAlexMHllc** [comment]
I fixed the issue a couple of days ago; also added remove. Will close issue.
