### ISSUE TITLE
Restrict client User permissions to documents

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#337]
Example screenshot

![restrict_document__permissions_to_client_documents](https://user-images.githubusercontent.com/11938477/34492135-444001a6-efb4-11e7-9b91-7a4720151364.jpg)

**Comment by b-solution** [comment]
1 - User can only see it's own documents
2 - If you want to restrict access ( remove doc/ edit ) you have to disable the access in setting => roles
