### ISSUE TITLE
Documents Managers breadcrumbs should all have links

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#374]
Need links on all document managers breadcrumbs, so user can return to parent level.
Also missing "Documents" as first breadcrumb.
Should remove DOCUMENTS header when not on main screen (top level with only folders).

Example screenshots

![document_managers_breadcrumbs_](https://user-images.githubusercontent.com/11938477/34742713-176e794a-f555-11e7-9a30-74a6d9000a8f.jpg)

**Comment by LAlexMHllc** [comment]
The last breadcrumb still needs a link so the user can go up a level to the parent folder.

If this is an issue, then maybe an alternative solution would be to add "Cancel" to the ACTIONS drop-down select that links to the parent folder (the last breadcrumb seen now without a link).

**Comment by b-solution** [comment]
![screenshot from 2018-01-19 22-21-23](https://user-images.githubusercontent.com/5988861/35172256-32b20c48-fd67-11e7-94de-0219f7b91227.png)
Documents will take you to the first page
Intake document will  point to parent folder ans the unlinked folder is the same page.

In general when you find a breadcrumb that does not have a link that mean you are on the same page of that link ( breadcrumb library )
