### ISSUE TITLE
When entering a date, the format is year, month, day however when it shows, is day month year.

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#389]
When entering a date, the format is year, month, day however when it shows, is day month year.

we really need it consistent and show year, month, day on all date screens like the edit screen

![image](https://user-images.githubusercontent.com/3675043/34781088-e8c8cb2e-f5f2-11e7-8ae1-4176a49f7c0f.png)

![image](https://user-images.githubusercontent.com/3675043/34781077-e1de6aa8-f5f2-11e7-853c-c9b1393f7d3f.png)

**Comment by b-solution** [comment]
link ?

**Comment by bluenevus** [comment]
Its all edit screens vs all show screens and all grids

--- Vr Frank

**Comment by b-solution** [comment]
@LAlexMHllc  it's a config in setting, we have to select on what format that date should be

**Comment by bluenevus** [comment]
I was able to change some of it globally like on the edit screen but it doesn't change it on the tables or show screen.  we need to make it really global and apply on all date fields

**Comment by b-solution** [comment]
Like Redmine do ( it show YEAR-month-day on date fields) but it render in different fomat that date
to be what we have done on setting.
