### ISSUE TITLE
my dashboard shows items in goals, plans and actions that are NOT overdue and NOT flagged when they should display

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#421]
![image](https://user-images.githubusercontent.com/3675043/34849259-d048dd3e-f6ef-11e7-86c5-2de9d6465728.png)

**Comment by LAlexMHllc** [comment]
Only shows main cases where Case Source = Self Referral. 
It will not show sub cases, even when self referral.
