### ISSUE TITLE
after saving action, rather than showing the action then plans below, it took me to the case

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#423]
![image](https://user-images.githubusercontent.com/3675043/34849451-6ba9453e-f6f0-11e7-90d5-b5f2df2c4c0e.png)

![image](https://user-images.githubusercontent.com/3675043/34849463-728e676c-f6f0-11e7-81ce-a8eded986337.png)

vs the show screen which is the screen goals and plans take you to after saving.  We want it to be the same for consistency

**Comment by b-solution** [comment]
we talked in skype about making all models to redirect to case when Creating, updating or deleting
