### ISSUE TITLE
in the manufacturer field AND product location field , please make that a google maps api search

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#434]
![image](https://user-images.githubusercontent.com/3675043/34851200-f826942a-f6f6-11e7-9750-b9475eeb5e2e.png)

Please remove the "Product Type" field

**Comment by LAlexMHllc** [comment]
Gmap api search not functioning for Product Location

![inventory_product_location_gmap](https://user-images.githubusercontent.com/11938477/35229751-30fc2576-ff62-11e7-8176-19b8e766f150.jpg)

**Comment by b-solution** [comment]
let me know if you still got that bug
