### ISSUE TITLE
[ERROR] client_documents#create (NoMethodError) "undefined method `set_link_to_appointment' for #<ClientDocumentsControl...

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#495]
New Client Profile - Documents get saved, but displays error screen

From screen: ".../client_documents/new"
Input Title, etc. then click Save btn
Error screen displays: ".../client_documents" even though successful create record

**Comment by bluenevus** [comment]
duplicate
