### ISSUE TITLE
Measurement screens - fix container with header for New and Show screens; fix breadcrumbs as well

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#504]
Add container border with header bar for New screen and Show screen; just like Edit screen (see below for sample screenshot)

Example Screenshot New Measurement

![measurement_new__container_header](https://user-images.githubusercontent.com/11938477/35237715-7e4ed820-ff79-11e7-90d2-82d6a86c2d61.jpg)

Example Screenshot Measurement (show screen)

![measurement_show__container_header](https://user-images.githubusercontent.com/11938477/35237891-da3f9188-ff79-11e7-804d-73735e875c91.jpg)

Sample Screenshot Edit Measurement

![measurement_edit__container_header](https://user-images.githubusercontent.com/11938477/35242255-03a8e9ea-ff87-11e7-82eb-525aaddaf0b2.jpg)

**Comment by bluenevus** [comment]
should be blood pressure not the number

**Comment by bluenevus** [comment]
measurement name

**Comment by LAlexMHllc** [comment]
Also fix breadcrumbs as per comments above
