### ISSUE TITLE
No warning when date end or date complete is earlier than date start

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#507]

**Comment by bluenevus** [comment]
Need to provide examples and screenshots so this is clear on the issue to the developer and on what screens

--- Vr Frank

**Comment by b-solution** [comment]
i did for action, goal, plan and cases

**Comment by LAlexMHllc** [comment]
This is one example, but should be for ALL date comparisons on all screens/tabs, record input
Screenshot Example

![date_before_accepted](https://user-images.githubusercontent.com/11938477/35572814-749f1f6c-05a3-11e8-992f-076d0f341d73.jpg)

**Comment by LAlexMHllc** [comment]
Case Records are not done

![dates_case_records](https://user-images.githubusercontent.com/11938477/35573053-f27cf260-05a3-11e8-892c-d40e3ff240e6.jpg)

**Comment by LAlexMHllc** [comment]
Goals dates not done

![dates_goals](https://user-images.githubusercontent.com/11938477/35573201-67073604-05a4-11e8-8265-78493f4138b6.jpg)

**Comment by LAlexMHllc** [comment]
Plans gave error for due date, but not complete date

Please check all. No more screenshots for now.
