### ISSUE TITLE
[ERROR] checklists#create (ActiveRecord::AssociationTypeMismatch) "ChecklistType(#72615460) expected, got String(#561162

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#519]
Error when tried to create new checklist template

**Comment by b-solution** [comment]
make screenshot to explain what did you put to got that error
thanks 
AND links too

**Comment by LAlexMHllc** [comment]
https://cms.microhealthllc.com/checklist_templates/new

![create_checklist_template](https://user-images.githubusercontent.com/11938477/35343353-71dab3d6-00f8-11e8-8522-72256b149e49.jpg)

**Comment by b-solution** [comment]
thanks, i got that issue. it was caused my checklist Type..
thanks anyway
