### ISSUE TITLE
he list we have for wiki is limited by the number of entries you can do else it doesn't show on the page,

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#54]
The list we have for wiki is limited by the number of entries you can do else it doesn't show on the page.  I have many more entries here but only these show
![image](https://cloud.githubusercontent.com/assets/3675043/24630308/2b8da732-188a-11e7-936a-5fde4348f2e3.png)

everytime I save another, it doesn't show on the wiki page

also, there is no way to remove it from being a subpage

**Comment by b-solution** [comment]
Could you see again

**Comment by bluenevus** [comment]
Its showing up now however, I still can move something that was a sup program into a main.  I made leagal a subpage of itself to try and make legal show and now its completely gone from the list.  Its truly not showing everything because some pages are missing however, anything new I add shows up.
