### ISSUE TITLE
collaborate and personal organizer showing on client menu

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#55]
for the client screen, it should say Client Organizer.  We just need to hide collaborate from the client screen.  The only place they should be able to see collaborate is on the same screen that has my clients

![image](https://cloud.githubusercontent.com/assets/3675043/24630494/f0431fee-188a-11e7-815c-7e62d6bfa35d.png)

**Comment by b-solution** [comment]
fixed i guess
