### ISSUE TITLE
Somestimes themes/nav menu incorrectly switches between CLIENT and ADMIN screens

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#552]
Screenshot Example

![admin_theme_incorrect_client_screen](https://user-images.githubusercontent.com/11938477/35691999-098eadae-0748-11e8-9fbd-25365031b647.jpg)

**Comment by b-solution** [comment]
In this case , the user is not a client,  He has case manager role ( check permission on his role)

**Comment by LAlexMHllc** [comment]
CLIENT screens should be light: Occupational History is one of the client screens, but in the image above the header and sidebar are incorrectly displayed when main content is Occupational History.

![client_screens__light_layout](https://user-images.githubusercontent.com/11938477/35979286-f75746e6-0cb5-11e8-8423-4f5a555e2f63.jpg)

**Comment by LAlexMHllc** [comment]
The Wiki screen also displayed with the light background instead of the dark background, but I did not get a screenshot.

**Comment by LAlexMHllc** [comment]
Screenshot of Events incorrectly displayed with CLIENT head/sidebar

![events__displayed_incorrect_layout](https://user-images.githubusercontent.com/11938477/36047345-d34e93b8-0da9-11e8-95d3-dc3d66a7ed6d.jpg)
