### ISSUE TITLE
Wiki page form: Sub-Page select should not include self or subpages as options

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#580]
Result is the page will not display using render_subpages(pages).

Screenshot Example using self

![wiki_sub_page_options_not_self](https://user-images.githubusercontent.com/11938477/36118695-f30c5ece-100b-11e8-9199-e08aab3aa2ec.jpg)

Screenshot Example using child (sub-page)

![wiki_sub_page_options_not_children](https://user-images.githubusercontent.com/11938477/36118722-06087c06-100c-11e8-9630-a8e9fb9fa5eb.jpg)

**Comment by LAlexMHllc** [comment]
Possible Solution 1:
wiki/all: Include drop-down select with all pages as options (like Sub-Page on form); when on change event will display that page.

Example

![wiki_all_select_page_dropdown](https://user-images.githubusercontent.com/11938477/36156557-62e2d3ce-10a5-11e8-8a3e-7a8596118ce6.jpg)

Possible Solution 2:
wiki/all: Maybe give user option to view listing with sub-pages (as is), as well as without (so all pages will display, even those with self or child error; then the errors can be fixed).

**Comment by b-solution** [comment]
i fixed the select options and made a migration to brake the endless loop in wiki
