### ISSUE TITLE
[ERROR] product_assigns#edit (ActionView::Template::Error) "undefined method `name' for nil:NilClass" An ActionView::Template::Error occurred in product_assigns#edit:  undefined method `name' for nil:NilClass app/views/layouts/base.html.erb:41:in `_app_views_layouts_base_html_erb__3305460666153713058_67282800'

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#582]
[ERROR] product_assigns#edit (ActionView::Template::Error) "undefined method `name' for nil:NilClass"
An ActionView::Template::Error occurred in product_assigns#edit:

undefined method `name' for nil:NilClass
app/views/layouts/base.html.erb:41:in `_app_views_layouts_base_html_erb__3305460666153713058_67282800'

**Comment by LAlexMHllc** [comment]
This error was linked to closed issue #537

![error_due_to_issue_537](https://user-images.githubusercontent.com/11938477/36163438-6f255e1a-10b7-11e8-9b29-29701cc9ac71.jpg)
