### ISSUE TITLE
ERROR] product_assigns#show (ActionView::Template::Error) "undefined method `name' for nil:NilClass" An ActionView::Template::Error occurred in product_assigns#show:  undefined method `name' for nil:NilClass app/views/layouts/base.html.erb:41:in `_app_views_layouts_base_html_erb___2675505336123887863_95740880'

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#585]
ERROR] product_assigns#show (ActionView::Template::Error) "undefined method `name' for nil:NilClass"
An ActionView::Template::Error occurred in product_assigns#show:

undefined method `name' for nil:NilClass
app/views/layouts/base.html.erb:41:in `_app_views_layouts_base_html_erb___2675505336123887863_95740880'

**Comment by LAlexMHllc** [comment]
This error is related to #582
See screenshot with name replaced by an inventory item that was removed. Item needs to be removed from the database.
