### ISSUE TITLE
Clicking Name from My Plans table where client is not user should login as client (as if client selected from Search Client), then display CLIENT Plan screen

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#594]
Screenshot Example

![case_record_screen_from_my_plans_link](https://user-images.githubusercontent.com/11938477/36445020-f3e7549e-164a-11e8-89c2-b9cca5370454.jpg)

**Comment by b-solution** [comment]
sorry, forgot to commit
