### ISSUE TITLE
Clicking Title from My Actions table where client is not user should login as client (as if client selected from Search Client), then display CLIENT Action screen

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#595]
Screenshot Example

![case_record_screen_from_my_actions_link](https://user-images.githubusercontent.com/11938477/36446217-a6253f92-164e-11e8-8564-03f2821419fc.jpg)

**Comment by b-solution** [comment]
sorry, forgot to commit
