### ISSUE TITLE
Clicking Title from My Appointments table where client is not user should login as client (as if client selected from Search Client), then display CLIENT Appointment screen

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#596]
Screenshot Example

![case_record_screen_from_my_appointments_link](https://user-images.githubusercontent.com/11938477/36449057-9c0ccbb6-1657-11e8-9e95-1bd31836e423.jpg)

**Comment by b-solution** [comment]
sorry, forgot to commit
