### ISSUE TITLE
Billings datepickers initial onfocus display incorrectly. Can this be fixed?

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#599]
The initial onfocus calendars display with current date, not the dates already in the textboxes.  This is the default behavior when input textbox is empty, but these fields have default initial input (one month prior and one month after).

Screenshot Example

![billings_datepicker](https://user-images.githubusercontent.com/11938477/36555531-4ca259f4-17d0-11e8-8be6-14bd0743ad76.jpg)

**Comment by b-solution** [comment]
don't think so
