### ISSUE TITLE
Change Home screen MH logo

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#604]
Change the MH logo image link to:
https://github.com/MicroHealthLLC/mCMS/blob/master/app/assets/images/MicroHealth-logo.svg

**Comment by bluenevus** [comment]
This is configured under settings

On Feb 26, 2018 11:55 AM, LAlexMHllc <notifications@github.com> wrote:

Change the MH logo image link to:
https://github.com/MicroHealthLLC/mCMS/blob/master/app/assets/images/MicroHealth-logo.svg<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicroHealthLLC%2FmCMS%2Fblob%2Fmaster%2Fapp%2Fassets%2Fimages%2FMicroHealth-logo.svg&data=01%7C01%7Cfrank.tucker%40microhealthllc.com%7C537f5c579ada41db8b5408d57d39cdc4%7C487ea2d67ea04a4b87736f4833ed2108%7C0&sdata=cjCs7lDU3VHaP25wiV1YNi5o8r5sro911cFSEMfto80%3D&reserved=0>

**Comment by bluenevus** [comment]
to change the logo you go into settings
