### ISSUE TITLE
Form does not retain Client Answers

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#646]
Client answers form and saves; then tries to edit form; answers not retained.

Screenshot Example

![client_edit_form_answers_not_retained](https://user-images.githubusercontent.com/11938477/37408313-2f7fbbbc-2772-11e8-8c68-57de42680fa7.jpg)

**Comment by bluenevus** [comment]
Name should be renamed to Description

**Comment by LAlexMHllc** [comment]
Label Name renamed Description; form element changed to textarea
