### ISSUE TITLE
Forms tab - table display

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#650]
The Forms tab/table should have: Name, Description, Organization, Form Type, Filled by, Date
(Note: "Filled by" is autopopulated by who ever is logged in)

Screenshot Example using Case Records screen - Forms tab/table

![case_records_forms_tab_table](https://user-images.githubusercontent.com/11938477/37530429-e2f56e00-290f-11e8-8e98-c1c35787966e.jpg)

**Comment by bluenevus** [comment]
We really need an enumeration that is Form Type.  They set it up in enumerations and configure the type of form in form administration similar to surveys.  THis way when they go through the tree, they see the type of form then the form name on the roll and scroll.  I imagine there will be many types of forms...many
