### ISSUE TITLE
Forms should have to be selected to be included, not automatically display in the Forms table

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#654]

**Comment by b-solution** [comment]
this will work like survey ?

**Comment by LAlexMHllc** [comment]
Yes for selecting a survey to take, BUT NOT the same function like Survey is now. The Forms and Survey modules are going to function like the other modules.

**Comment by b-solution** [comment]
i guess with #658 this will be fixed, so we select the form from that dropdown instead of what we had
