### ISSUE TITLE
Client Document Form and Case Record Document Form: Are the "private" options functioning as expected when checked?

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#664]
Screenshot Example

![document_private_option_checked](https://user-images.githubusercontent.com/11938477/37540924-2964c3bc-292f-11e8-9aad-5c69f44406c6.jpg)

**Comment by b-solution** [comment]
Yes.
it was not working before. ( any one with super role privilege can read the athor document)
now it's fixed
