### ISSUE TITLE
Case Record Case Note Form and Appointment Note Form: Are the "private" options functioning as expected when checked?

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#665]
Screenshot Examples

![case_note_private_option_checked](https://user-images.githubusercontent.com/11938477/37541223-24ebf250-2930-11e8-9733-40b28bdf1448.jpg)

![appt_note_private_option_checked](https://user-images.githubusercontent.com/11938477/37542037-22254712-2933-11e8-8c05-2bfd04b1d0d5.jpg)

**Comment by b-solution** [comment]
working now
