### ISSUE TITLE
Identification ACTION Cancel path, form Cancel button path: check and fix where necessary

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#668]

**Comment by b-solution** [comment]
could you give me some link to fix them. ?

**Comment by LAlexMHllc** [comment]
Screenshot Examples

My Profile: "../users/edit#tabs-identification"
Client Profile: "../profile_record#tabs-identification"

![identification_profile_cancel_breadcrumb_links](https://user-images.githubusercontent.com/11938477/37834659-9f345a12-2e84-11e8-8222-e408b6971dac.jpg)

**Comment by bluenevus** [comment]
I still don't understand the issue here on the path

**Comment by b-solution** [comment]
when i cancel fro adding/editing  identification i should redirected to identification tab not to extend demographics tab
