### ISSUE TITLE
Editing Form does not always update answers; date needs to update on save

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#686]

**Comment by b-solution** [comment]
fixed, don't forget to migrate

**Comment by LAlexMHllc** [comment]
date needs to update on save

**Comment by LAlexMHllc** [comment]
Option 1) Only one Date column: input New form; updates on Edit
Option 2) Two date columns: Date column input (New form record date); Last Updated column (updates on Edit)

**Comment by b-solution** [comment]
could you send me a link for a form, i've tested and it's working

**Comment by LAlexMHllc** [comment]
Screenshot Example

![edit_form_does_not_update](https://user-images.githubusercontent.com/11938477/38041346-7a8f0be0-327f-11e8-9864-942e3938d406.jpg)

**Comment by LAlexMHllc** [comment]
Date never updates on Edit/Save
ONLY the Case Records - Forms answers are updating, NOT the other forms. 
Test Socioeconomic or Health (answers nor dates updating)
