### ISSUE TITLE
Remove Identification from Client Profile - Edit Contact screen

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mCMS#699]
Screenshot Example

![client_profile_contact_identification](https://user-images.githubusercontent.com/11938477/38739532-36d209f8-3f03-11e8-9cef-9b15cb52f371.jpg)

**Comment by b-solution** [comment]
Moved it to contact information

**Comment by LAlexMHllc** [comment]
Please remove this
